#!/usr/bin/sh

if [ -z ${THEME+x} ]; then THEME="$(cat ~/.config/archie/theme_system)"; fi

pgrep -x sxhkd > /dev/null || sxhkd >>/tmp/sxhkd.log 2>&1 &

# query monitor names:
# bspc query -M --names
bspc monitor HDMI-0 -d 1 2 3 4 5 6 7 8
#bspc monitor HDMI-1 -d 1 3 5 7 9
#bspc monitor HDMI-2 -d 2 4 6 8 0

bspc config click_to_focus any
bspc config initial_polarity second_child

bspc config border_width         2
bspc config window_gap          20
#bspc config bottom_padding	20 lowers windows sometimes but buggy

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      false

# application rules (find name with xprop)
bspc rule -a 'Steam' desktop=^7
#bspc rule -a 'rdesktop' desktop=^5

#bspc rule -a 'Nemo' state=floating
bspc rule -a 'Nm-connection-editor' state=floating
bspc rule -a 'gnome-calculator' state=floating
bspc rule -a 'Ulauncher' border=off

# stop x shaped cursor from apprearing outside windows
xsetroot -cursor_name left_ptr &

if [ "$THEME" = "sunset" ]
then
	# sunset theme
	feh --bg-fill ~/Pictures/bg/ruben-begues-desert.jpg --bg-fill ~/Pictures/bg/laura-vinck-Hyu76loQLdk-unsplash.jpg
	bspc config normal_border_color		\#4b5e56
	bspc config active_border_color		\#4b5e56
	bspc config presel_feedback_color	\#888888
	bspc config focused_border_color	\#66d4a2
elif [ "$THEME" = "grass" ]
then
	# grass theme
	feh --bg-fill ~/Pictures/bg/bruno-martins-k1_UO1MGszs-unsplash.jpg --bg-fill ~/Pictures/bg/maddy-baker-chvHxKFpoUA-unsplash.jpg
	bspc config normal_border_color		\#444444
	bspc config active_border_color		\#444444
	bspc config presel_feedback_color	\#888888
	bspc config focused_border_color	\#b46b18
elif [ "$THEME" = "coral" ]
then
	# coral theme
	feh --bg-fill ~/Pictures/bg/david-clode-nv5wWuPH-Go-unsplash.jpg --bg-fill ~/Pictures/bg/david-clode-5pXwpRw6O8c-unsplash.jpg
	bspc config normal_border_color		\#444444
	bspc config active_border_color		\#444444
	bspc config presel_feedback_color	\#888888
	bspc config focused_border_color	\#00aa33
elif [ "$THEME" = "flowers" ]
then
	# flowers theme
	feh --bg-fill ~/Pictures/bg/flowers_yousef-espanioly-0iOOw41DZ28-unsplash.jpg --bg-fill ~/Pictures/bg/flowers1_atul-vinayak-J1t1FY__6EI-unsplash.jpg
	bspc config normal_border_color		\#444444
	bspc config active_border_color		\#444444
	bspc config presel_feedback_color	\#888888
	bspc config focused_border_color	\#4f589c
elif [ "$THEME" = "yellow" ]
then
    # yellow theme
	feh --bg-fill ~/Pictures/flourescence/5-flourescence.jpg --bg-fill ~/Pictures/flourescence/rot-90/4-flourescence.jpg
	bspc config normal_border_color     \#444444
	bspc config active_border_color     \#444444
	bspc config presel_feedback_color   \#888888
	bspc config focused_border_color    \#88bb00
else
	# dark theme default
	export THEME="dark"
	feh --bg-fill ~/Pictures/bg/david-troeger-iLeIDlfNgpo-unsplash.jpg --bg-fill ~/Pictures/bg/andre-iv-cQXKmQAQy3w-unsplash.jpg
	bspc config normal_border_color		\#444444
	bspc config active_border_color		\#444444
	bspc config presel_feedback_color	\#888888
	#bspc config focused_border_color	\#469394
	bspc config focused_border_color	\#007755
fi

# enable recording of node focus history
bspc wm --record-history on;

# external rules
#bspc config external_rules_command "$HOME/.config/bspwm/spotify-rules";

# start polybar
if [ "$THEME" = "sunset" ]
then
	# sunet theme
	FOREGROUND="#cc000000" FOREGROUND_BR="#ccffffff" UNDERLINE="#ff7affc6" TRANSPARENT="#33bfffe4" RED="#66e64949" GREY="#55000000" GREY_BR="#55ffffff" CPU_RAMP="#ddbf3c28" $HOME/.config/polybar/launch.sh
elif [ "$THEME" = "coral" ]
then
	# coral theme
	FOREGROUND="#ccffffff" UNDERLINE="#ff54ff80" TRANSPARENT="#44404f4f" RED="#66e64949" GREY="#55dddddd" CPU_RAMP="#4ed96a" $HOME/.config/polybar/launch.sh
elif [ "$THEME" = "grass" ]
then
	# grass theme
	FOREGROUND="#cc000000" FOREGROUND_BR="#ccffffff" UNDERLINE="#ff784810" TRANSPARENT="#44594c3e" RED="#66e64949" GREY="#66000000" GREY_BR="#55ffffff" CPU_RAMP="#ddbf3c28" $HOME/.config/polybar/launch.sh
elif [ "$THEME" = "flowers" ]
then
	# flowers theme
	FOREGROUND="#ccffffff" FOREGROUND_BR="#ccffffff" UNDERLINE="#57c4ff" TRANSPARENT="#552c424d" TRANSPARENT_BR="445c7f91" RED="#66e64949" GREY="#44dddddd" GREY_BR="#55ffffff" CPU_RAMP="#7affc6" $HOME/.config/polybar/launch.sh
elif [ "$THEME" = "yellow" ]
then
    # yellow theme
	FOREGROUND="#ccffffff" UNDERLINE="#ffaaff33" TRANSPARENT="#33bfffe4" RED="#66e64949" GREY="#55ffffff" CPU_RAMP="#4ed96a" $HOME/.config/polybar/launch.sh
else
	# dark theme default
	FOREGROUND="#ccffffff" UNDERLINE="#ffe65572" TRANSPARENT="#444f4f4f" RED="#66e64949" GREY="#55ffffff" CPU_RAMP="#7affc6" $HOME/.config/polybar/launch.sh
fi

# start dunst desktop notification manager (ctrl + space to dismiss notifications)
#if [[ -z $(pidof dunst) ]]; then
#    dunst &
#fi

# start polkit authentication
#if ! pgrep 'polkit-dumb' &> /dev/null ; then polkit-dumb-agent &> $HOME/.config/polkit-dumb-agent.pid ; fi
