#!/bin/sh

# This is the example configuration file for river.
#
# If you wish to edit this, you will probably want to copy it to
# $XDG_CONFIG_HOME/river/init or $HOME/.config/river/init first.
#
# See the river(1), riverctl(1), and rivertile(1) man pages for complete
# documentation.

# Note: the "Super" modifier is also known as Logo, GUI, Windows, Mod4, etc.

# APPS

#riverctl map normal Super Return spawn kitty
riverctl map normal Super Return spawn alacritty
riverctl map normal Super Space spawn ulauncher-toggle
riverctl map normal Super F spawn firefox
#riverctl map normal Super E spawn 'io.elementary.files -n'
riverctl map normal Super E spawn nemo
riverctl map normal Super C spawn code
riverctl map normal Super S spawn /home/david/Documents/bin/screenshot.sh

# SYSTEM

# Super+Q to close the focused view
riverctl map normal Super Q close

# Super+\ to exit river
riverctl map normal Super \ exit

# Super+J and Super+K to focus the next/previous view in the layout stack
riverctl map normal Alt H focus-view left
riverctl map normal Alt J focus-view down
riverctl map normal Alt K focus-view up
riverctl map normal Alt L focus-view right

riverctl map normal Super H focus-view left
riverctl map normal Super J focus-view down
riverctl map normal Super K focus-view up
riverctl map normal Super L focus-view right

# Super+Shift+J and Super+Shift+K to swap the focused view with the next/previous
# view in the layout stack
riverctl map normal Alt+Shift H swap left
riverctl map normal Alt+Shift J swap down
riverctl map normal Alt+Shift K swap up
riverctl map normal Alt+Shift L swap right

riverctl map normal Super+Shift H swap left
riverctl map normal Super+Shift J swap down
riverctl map normal Super+Shift K swap up
riverctl map normal Super+Shift L swap right

# Super+Period and Super+Comma to focus the next/previous output
riverctl map normal Alt Period focus-output next
riverctl map normal Super Period focus-output next
riverctl map normal Alt Comma focus-output previous
riverctl map normal Super Comma focus-output next

# Super+Shift+{Period,Comma} to send the focused view to the next/previous output
riverctl map normal Alt+Shift Period send-to-output -current-tags next
riverctl map normal Super+Shift Period send-to-output -current-tags next
riverctl map normal Alt+Shift Comma send-to-output -current-tags previous
riverctl map normal Super+Shift Comma send-to-output -current-tags previous

# Super+Return to bump the focused view to the top of the layout stack
#riverctl map normal Super Return zoom

# Super+H and Super+L to decrease/increase the main ratio of rivertile(1)
#riverctl map normal Super H send-layout-cmd rivertile "main-ratio -0.05"
#riverctl map normal Super L send-layout-cmd rivertile "main-ratio +0.05"

# Super+Shift+H and Super+Shift+L to increment/decrement the main count of rivertile(1)
#riverctl map normal Super+Shift H send-layout-cmd rivertile "main-count +1"
#riverctl map normal Super+Shift L send-layout-cmd rivertile "main-count -1"

# Super+Alt+{H,J,K,L} to move views
#riverctl map normal Alt H move left 100
#riverctl map normal Alt J move down 100
#riverctl map normal Alt K move up 100
#riverctl map normal Alt L move right 100

# Super+Alt+Control+{H,J,K,L} to snap views to screen edges
#riverctl map normal Super+Alt+Control H snap left
#riverctl map normal Super+Alt+Control J snap down
#riverctl map normal Super+Alt+Control K snap up
#riverctl map normal Super+Alt+Control L snap right

# Super+Alt+Shift+{H,J,K,L} to resize views
#riverctl map normal Super+Alt+Shift H resize horizontal -100
#riverctl map normal Super+Alt+Shift J resize vertical 100
#riverctl map normal Super+Alt+Shift K resize vertical -100
#riverctl map normal Super+Alt+Shift L resize horizontal 100

# Super + Left Mouse Button to move views
riverctl map-pointer normal Super BTN_LEFT move-view

# Super + Right Mouse Button to resize views
riverctl map-pointer normal Super BTN_RIGHT resize-view

# Super + Middle Mouse Button to toggle float
riverctl map-pointer normal Super BTN_MIDDLE toggle-float

# increment/decrement tags
riverctl map normal Super N increment-focused-tags 8
riverctl map normal Super P decrement-focused-tags 8
riverctl map normal Super+Shift N increment-view-tags 8
riverctl map normal Super+Shift P decrement-view-tags 8

riverctl map normal Alt N increment-focused-tags 8
riverctl map normal Alt P decrement-focused-tags 8
riverctl map normal Alt+Shift N increment-view-tags 8
riverctl map normal Alt+Shift P decrement-view-tags 8

#riverctl map-pointer normal Alt BTN_EXTRA increment-focused-tags 8
#riverctl map-pointer normal Alt BTN_SIDE decrement-focused-tags 8

# previous tags
riverctl map normal Super TAB focus-previous-tags

for i in $(seq 1 8)
do
    tags=$((1 << ($i - 1)))

    # Super+[1-9] to focus tag [0-8]
    riverctl map normal Alt $i set-focused-tags $tags

    # Super+Shift+[1-9] to tag focused view with tag [0-8]
    riverctl map normal Alt+Shift $i set-view-tags $tags

    # Super+Ctrl+[1-9] to toggle focus of tag [0-8]
    riverctl map normal Super $i toggle-focused-tags $tags

    # Super+Shift+Ctrl+[1-9] to toggle tag [0-8] of focused view
    riverctl map normal Super+Shift $i toggle-view-tags $tags
done

# Super+0 to focus all tags
# Super+Shift+0 to tag focused view with all tags
all_tags=$(((1 << 32) - 1))
riverctl map normal Super 0 set-focused-tags $all_tags
riverctl map normal Super+Shift 0 set-view-tags $all_tags

riverctl map normal Super T toggle-float
riverctl map normal Super G toggle-fullscreen

# Super+{Up,Right,Down,Left} to change layout orientation
riverctl map normal Super Up    send-layout-cmd rivertile "main-location top"
riverctl map normal Super Right send-layout-cmd rivertile "main-location right"
riverctl map normal Super Down  send-layout-cmd rivertile "main-location bottom"
riverctl map normal Super Left  send-layout-cmd rivertile "main-location left"

# Declare a passthrough mode. This mode has only a single mapping to return to
# normal mode. This makes it useful for testing a nested wayland compositor
riverctl declare-mode passthrough

# Super+F11 to enter passthrough mode
riverctl map normal Super F11 enter-mode passthrough

# Super+F11 to return to normal mode
riverctl map passthrough Super F11 enter-mode normal

# Various media key mapping examples for both normal and locked mode which do
# not have a modifier
for mode in normal locked
do
    # Eject the optical drive (well if you still have one that is)
    riverctl map $mode None XF86Eject spawn 'eject -T'

    # Control pulse audio volume with pamixer (https://github.com/cdemoulins/pamixer)
    riverctl map -repeat $mode None XF86AudioRaiseVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ +2%'
    riverctl map -repeat $mode None XF86AudioLowerVolume  spawn 'pactl set-sink-volume @DEFAULT_SINK@ -2%'
    riverctl map $mode None XF86AudioMute         spawn 'pactl set-sink-mute @DEFAULT_SINK@ toggle'

    # Control MPRIS aware media players with playerctl (https://github.com/altdesktop/playerctl)
    riverctl map $mode None XF86AudioPlay  spawn 'mpris2controller PlayPause'
    #riverctl map $mode None XF86AudioPrev  spawn 'mpris2controller Previous'
    #riverctl map $mode None XF86AudioNext  spawn 'mpris2controller Next'
    riverctl map $mode None XF86AudioPrev  spawn 'playerctl previous'
    riverctl map $mode None XF86AudioNext  spawn 'playerctl next'

    # Control screen backlight brightness with light (https://github.com/haikarainen/light)
    riverctl map $mode None XF86MonBrightnessUp   spawn 'light -A 5'
    riverctl map $mode None XF86MonBrightnessDown spawn 'light -U 5'
done

# volume with mouse
riverctl map-pointer normal Alt+Shift+BTN_GEAR_DOWN spawn 'pactl set-sink-volume @DEFAULT_SINK@ +2%'
riverctl map-pointer normal Alt+Shift+BTN_GEAR_UP   spawn 'pactl set-sink-volume @DEFAULT_SINK@ -2%'

# Set default background and border color
riverctl background-color 0x002b36
riverctl border-color-focused 0x67AC68
riverctl border-color-unfocused 0x586e75

# Set keyboard repeat rate
riverctl set-repeat 35 200

# Make certain views start floating
riverctl float-filter-add app-id float
riverctl float-filter-add title "popup title with spaces"

# Set app-ids and titles of views which should use client side decorations
riverctl csd-filter-add app-id "gedit"

# normal, disabled
riverctl focus-follows-cursor normal

# Set the default layout generator to be rivertile and start it.
# River will send the process group of the init executable SIGTERM on exit.
riverctl default-layout rivertile
rivertile -main-ratio 0.5 -view-padding 8 -outer-padding 8 -main-location left &> /tmp/rivertile.log &

# riverctl send-layout-cmd rivertile "main-location left"

riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad natural-scroll enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad tap enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad drag enabled
riverctl input pointer-2-14-ETPS/2_Elantech_Touchpad drag-lock enabled

# rules
riverctl rule-add ssd
riverctl rule-add -app-id ulauncher csd
riverctl rule-add -app-id steam tags 64 # ws7
#riverctl rule-add -app-id ulauncher position 660 250

# new windows at bottom of stack
riverctl attach-mode bottom

# monitor arrangement
wlr-randr --output DP-1 --pos 0,250 --adaptive-sync disabled
wlr-randr --output DP-2 --transform 270 --pos 2560,0 --adaptive-sync disabled

# launcher
if [[ -z $(pidof ulauncher) ]]; then
	ulauncher --hide-window &> /tmp/ulauncher.log &
fi

if [[ -z $(pidof ulauncher) ]]; then
	mpd-mpris &> /tmp/mpd-mpris.log &
fi

# notification daemon
dunst &> /tmp/dunst.log &

# set theme and start waybar
export THEME=$(cat ~/.config/archie/theme_system)
set-theme $THEME &
