#!/bin/bash

# autocompletion list in /usr/share/zsh/site-functions/_set-theme
# compdef _set-theme set-theme

export THEME="$1"
echo "${THEME}" > ~/.config/archie/theme_system

killall swaybg

if [ "$THEME" = "plains" ]; then
	swaybg -m fill -i ~/Pictures/bg/bruno-martins-k1_UO1MGszs-unsplash.jpg > /tmp/swaybg.tmp 2>&1 &
        GTK_THEME="Desert-Teal-light-40"
	ln -fs ~/.config/waybar/theme-colors/plains.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "forest" ]; then
	swaybg -m fill -i ~/Pictures/bg/forest.jpg > /tmp/swaybg.tmp 2>&1 &
        GTK_THEME="Desert-Teal-Dark-40"
	ln -fs ~/.config/waybar/theme-colors/forest.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "flowers" ]; then
	swaybg -m fill -i ~/Pictures/bg/flowers_yousef-espanioly-0iOOw41DZ28-unsplash.jpg > /tmp/swaybg.tmp 2>&1 &
        GTK_THEME="Desert-Teal-Dark-40"
	# TODO
	ln -fs ~/.config/waybar/theme-colors/flowers.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0x4f589c
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "mountain" ]; then
	swaybg -m fill -i ~/Pictures/bg/tobias-keller-73F4pKoUkM0-unsplash.jpg > /tmp/swaybg.tmp 2>&1 &
        GTK_THEME="Desert-Teal-Dark-40"
	# TODO
	ln -fs ~/.config/waybar/theme-colors/mountain.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "shodan" ]; then
	swaybg -m fill -i ~/Pictures/bg/shodan.png > /tmp/swaybg.tmp 2>&1 &
        GTK_THEME="GreenCodded-theme"
	# TODO
	ln -fs ~/.config/waybar/theme-colors/shodan.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0x00aa33
	riverctl border-color-unfocused 0x444444
else
	# dark theme (default)
	swaybg -m fill -i ~/Pictures/bg/david-troeger-iLeIDlfNgpo-unsplash.jpg > /tmp/swaybg.tmp 2>&1 &
        GTK_THEME="Desert-Teal-Dark-40"
	# TODO
	ln -fs ~/.config/waybar/theme-colors/dark.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0x007755
	riverctl border-color-unfocused 0x444444
fi

killall waybar
waybar > /tmp/waybar.log 2>&1 &

ICON_THEME="Obsidenza-Sand"
CURSOR_THEME="Breeze_Hacked_Green"
FONT_NAME="Iosevka SS18, 11"

echo "$GTK_THEME" > ~/.config/archie/theme_gtk
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME"
gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR_THEME"
gsettings set org.gnome.desktop.interface font-name "$FONT_NAME"
sed -i "/gtk-theme-name/c\gtk-theme-name=$GTK_THEME" ~/.config/gtk-3.0/settings.ini
sed -i "/gtk-icon-theme-name/c\gtk-icon-theme-name=$ICON_THEME" ~/.config/gtk-3.0/settings.ini
sed -i "/gtk-icon-theme-name/c\gtk-icon-theme-name=$ICON_THEME" ~/.config/gtk-4.0/settings.ini
sed -i "/gtk-cursor-theme-name/c\gtk-cursor-theme-name=$CURSOR_THEME" ~/.config/gtk-3.0/settings.ini
sed -i "/gtk-cursor-theme-name/c\gtk-cursor-theme-name=$CURSOR_THEME" ~/.config/gtk-4.0/settings.ini
