#!/bin/sh

# autocompletion list in /usr/share/zsh/site-functions/_set-theme

export THEME="$1"
echo "${THEME}" > ~/.config/theme/system_theme

if [ "$THEME" = "light" ]; then
	gsettings set org.gnome.desktop.interface gtk-theme 'WhiteSur-light-blue';
	wallpaper.sh ~/Pictures/wallpapers/4.jpg
elif [ "$THEME" = "glass" ]; then
	gsettings set org.gnome.desktop.interface gtk-theme 'WhiteSur-light-blue';
	wallpaper.sh ~/Pictures/wallpapers/jakob-owens-zYD_XzNyRyo-unsplash.jpg
elif [ "$THEME" = "sunset" ]; then
	gsettings set org.gnome.desktop.interface gtk-theme 'WhiteSur-dark-blue';
	wallpaper.sh ~/Pictures/wallpapers/luke-chesser-zFaSM1hz02c-unsplash.jpg
elif [ "$THEME" = "dark" ]; then
	gsettings set org.gnome.desktop.interface gtk-theme 'WhiteSur-dark-blue';
	wallpaper.sh ~/Pictures/wallpapers/milad-fakurian-nY14Fs8pxT8-unsplash.jpg
fi
