#!/bin/sh

# autocompletion list in /usr/share/zsh/site-functions/_set-theme-bspwm

export THEME="$1"
. ~/.config/bspwm/bspwmrc
echo "${THEME}" > ~/.config/archie/theme_system

#if [ "$THEME" = "sunset" ]; then echo "Yaru-Orange" > ~/.config/theme_gtk;
#elif [ "$THEME" = "grass" ]; then echo "Yaru-Orange" > ~/.config/theme_gtk;
#elif [ "$THEME" = "coral" ]; then echo "Yaru-Orange-dark" > ~/.config/theme_gtk;
#elif [ "$THEME" = "flowers" ]; then echo "Yaru-Orange-dark" > ~/.config/theme_gtk;
#elif [ "$THEME" = "dark" ]; then echo "Yaru-Orange-dark" > ~/.config/theme_gtk;
#else echo "Yaru-Orange-dark" > ~/.config/theme_gtk; fi
if [ "$THEME" = "grass" ]; then
	#GTK_THEME="Catppuccin-Latte-Standard-Lavender-light"
	#ICON_THEME="Papirus"
	GTK_THEME="Desert-Teal-light-40"
elif [ "$THEME" = "plains" ]; then
	GTK_THEME="Desert-Teal-light-40"
elif [ "$THEME" = "mountain" ]; then
	#GTK_THEME="Desert-Teal-light-40"
	GTK_THEME="Desert-Teal-Dark-40"
elif [ "$THEME" = "lake" ]; then
	GTK_THEME="Desert-Teal-light-40"
	#GTK_THEME="Catppuccin-Latte-Standard-Lavender-light"
elif [ "$THEME" = "shodan" ]; then
	GTK_THEME="GreenCodded-theme"
else
	GTK_THEME="Desert-Teal-Dark-40"
	#GTK_THEME="Catppuccin-Mocha-Standard-Lavender-dark"
	#ICON_THEME="Papirus-Dark"
fi
ICON_THEME="Obsidenza-Sand"

echo "$GTK_THEME" > ~/.config/archie/theme_gtk
gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME"
sed -i "/gtk-theme-name/c\gtk-theme-name = $GTK_THEME" ~/.config/gtk-3.0/settings.ini
sed -i "/gtk-icon-theme-name/c\gtk-icon-theme-name = $ICON_THEME" ~/.config/gtk-3.0/settings.ini
