#!/bin/bash

# autocompletion list in /usr/share/zsh/site-functions/_set-theme
# compdef _set-theme set-theme
export THEME="$1"
echo "${THEME}" > ~/.config/archie/theme_system

#ICON_THEME="Obsidenza-Sand"
ICON_THEME="Obsidian-Sand"
CURSOR_THEME="Breeze_Hacked_Green"
FONT_NAME="Iosevka SS18, 11"

if [ "$THEME" = "plains" ]; then
	export BG_IMG=~/Pictures/bg/bruno-martins-k1_UO1MGszs-unsplash.jpg
    GTK_THEME="Desert-Teal-light-40"
	ln -fs ~/.config/waybar/theme-colors/plains.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "forest" ]; then
	export BG_IMG=~/Pictures/bg/forest.jpg
    GTK_THEME="Desert-Teal-Dark-40"
	ln -fs ~/.config/waybar/theme-colors/forest.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "flowers" ]; then
	export BG_IMG=~/Pictures/bg/flowers_yousef-espanioly-0iOOw41DZ28-unsplash.jpg
    GTK_THEME="Skeuos-Violet-Dark"
	ICON_THEME="Obsidian-Purple"
	ln -fs ~/.config/waybar/theme-colors/flowers.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0x4f589c
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "mountain" ]; then
	export BG_IMG=~/Pictures/bg/tobias-keller-73F4pKoUkM0-unsplash.jpg
    GTK_THEME="Desert-Teal-Dark-40"
	ln -fs ~/.config/waybar/theme-colors/mountain.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "lake" ]; then
	export BG_IMG=~/Pictures/bg/danny-postma-rdxj6E_v7l0-unsplash.jpg
    GTK_THEME="Desert-Teal-light-40"
	ln -fs ~/.config/waybar/theme-colors/flowers.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0x4f589c
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "church" ]; then
	export BG_IMG=~/Pictures/bg/zane-muir-P_PPnp-ai1Q-unsplash.jpg
    GTK_THEME="oomox-gruvbox-dark-soft"
	ln -fs ~/.config/waybar/theme-colors/mountain.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "bush" ]; then
	export BG_IMG=~/Pictures/bg/yvon-hoogers-lJINays-OpA-unsplash.jpg
    GTK_THEME="Desert-Teal-Dark-40"
	ln -fs ~/.config/waybar/theme-colors/mountain.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0xb46b18
	riverctl border-color-unfocused 0x444444
elif [ "$THEME" = "shodan" ]; then
	export BG_IMG=~/Pictures/bg/shodan.png
    GTK_THEME="GreenCodded-theme"
	ICON_THEME="Obsidian-Green"
	ln -fs ~/.config/waybar/theme-colors/shodan.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0x00aa33
	riverctl border-color-unfocused 0x444444
else
	# dark theme (default)
	export BG_IMG=~/Pictures/bg/david-troeger-iLeIDlfNgpo-unsplash.jpg
    GTK_THEME="Desert-Teal-Dark-40"
	ln -fs ~/.config/waybar/theme-colors/dark.css ~/.config/waybar/theme-colors.css
	riverctl border-color-focused 0x007755
	riverctl border-color-unfocused 0x444444
fi

killall swaybg
ln -snf $BG_IMG ~/.config/archie/bg-img
swaybg -m fill -i ~/.config/archie/bg-img > /tmp/swaybg.tmp 2>&1 &

killall waybar
waybar > /tmp/waybar.log 2>&1 &

gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME"
sed -i "/gtk-theme-name/c\gtk-theme-name=$GTK_THEME" ~/.config/gtk-3.0/settings.ini
echo "$GTK_THEME" > ~/.config/archie/theme_gtk

gsettings set org.gnome.desktop.interface icon-theme "$ICON_THEME"
sed -i "/gtk-icon-theme-name/c\gtk-icon-theme-name=$ICON_THEME" ~/.config/gtk-3.0/settings.ini
sed -i "/gtk-icon-theme-name/c\gtk-icon-theme-name=$ICON_THEME" ~/.config/gtk-4.0/settings.ini

gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR_THEME"
sed -i "/gtk-cursor-theme-name/c\gtk-cursor-theme-name=$CURSOR_THEME" ~/.config/gtk-3.0/settings.ini
sed -i "/gtk-cursor-theme-name/c\gtk-cursor-theme-name=$CURSOR_THEME" ~/.config/gtk-4.0/settings.ini
sed -i "/Inherits =/c\Inherits = $CURSOR_THEME" ~/.local/share/icons/default/index.theme
riverctl xcursor-theme "$CURSOR_THEME"

gsettings set org.gnome.desktop.interface font-name "$FONT_NAME"
